runtime: nodejs12 # or nodejs10

instance_class: F2

env_variables:
  PORT: ""
  DB_NAME: "node-crud-app"
  DB_USERNAME: "blazhkos"
  DB_PASSWORD: "1617"
  DB_HOST: "34.89.19.253"



handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
